import type { ImageLoaderProps } from "next/image";

/**
 * Custom `next/image` loader for the static export.
 *
 * Local images are referenced by their optimized source path, e.g.
 * `/media/img/gallery/cover.webp`. Variants are generated by
 * scripts/optimize-media.mjs as `<name>-<width>.webp` next to it, so we only
 * have to swap the suffix. Remote (absolute) URLs are returned unchanged.
 *
 * NEXT_PUBLIC_MEDIA_BASE_URL lets every asset move to a CDN / object store
 * later without touching components.
 */
const BASE = (process.env.NEXT_PUBLIC_MEDIA_BASE_URL ?? "").replace(/\/$/, "");

export default function imageLoader({ src, width }: ImageLoaderProps): string {
  if (/^(https?:)?\/\//.test(src) || src.startsWith("data:")) return src;
  if (!src.startsWith("/media/img/")) return `${BASE}${src}`;
  return `${BASE}${src.replace(/\.webp$/, "")}-${width}.webp`;
}
