"use client";

import { readSettings, subscribeSettings } from "@/lib/settings";
import { biquad, duck, getMixer } from "./mixer";

/**
 * Interface sounds for a CRT / terminal runtime, synthesized on the fly:
 * oscillators, filtered noise and envelopes. No samples, no downloads,
 * nothing licensed: every sound is generated by this file.
 *
 * Mixing: each voice gets its own gain into the sfx bus; at most MAX_VOICES
 * ring at once (the oldest is faded out), the same sound can't retrigger
 * within 30 ms (no machine-gun clicks), and every sound briefly ducks the
 * music so the two sit together instead of fighting.
 */
export type SfxName =
  | "click"
  | "tap"
  | "toggleOn"
  | "toggleOff"
  | "open"
  | "close"
  | "key"
  | "success"
  | "error"
  | "toast"
  | "glitch"
  | "hit"
  | "miss"
  | "win"
  | "lose"
  | "step"
  | "bronze"
  | "silver"
  | "gold"
  | "platinum"
  | "diamond"
  | "master"
  | "rankup";

const MAX_VOICES = 8;
const voices: { out: GainNode; end: number }[] = [];
const lastPlayed = new Map<SfxName, number>();
let noiseBuf: AudioBuffer | null = null;
let wired = false;

/** Some sounds are felt more than heard; these skip the music duck. */
const NO_DUCK = new Set<SfxName>(["key", "step", "click"]);

function level() {
  const s = readSettings();
  return s.sfx ? Math.max(0, Math.min(1, s.sfxVolume / 100)) : 0;
}

function wire() {
  if (wired) return;
  wired = true;
  const { sfx, ctx } = getMixer();
  sfx.gain.value = level();
  subscribeSettings(() => sfx.gain.setTargetAtTime(level(), ctx.currentTime, 0.03));
}

function noise(ctx: AudioContext) {
  if (!noiseBuf) {
    noiseBuf = ctx.createBuffer(1, ctx.sampleRate, ctx.sampleRate);
    const d = noiseBuf.getChannelData(0);
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
  }
  return noiseBuf;
}

interface ToneOpts {
  type?: OscillatorType;
  f0: number;
  f1?: number;
  dur: number;
  gain?: number;
  attack?: number;
  lp?: number;
}

function tone(ctx: AudioContext, out: AudioNode, t: number, { type = "sine", f0, f1 = f0, dur, gain = 0.2, attack = 0.003, lp }: ToneOpts) {
  const o = ctx.createOscillator();
  o.type = type;
  o.frequency.setValueAtTime(f0, t);
  if (f1 !== f0) o.frequency.exponentialRampToValueAtTime(f1, t + dur);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(gain, t + attack);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  let node: AudioNode = o;
  if (lp) {
    const f = biquad(ctx);
    f.type = "lowpass";
    f.frequency.value = lp;
    node = node.connect(f);
  }
  node.connect(g).connect(out);
  o.start(t);
  o.stop(t + dur + 0.02);
}

interface NoiseOpts {
  dur: number;
  gain?: number;
  filter?: BiquadFilterType;
  f0: number;
  f1?: number;
  q?: number;
}

function hiss(ctx: AudioContext, out: AudioNode, t: number, { dur, gain = 0.1, filter = "bandpass", f0, f1 = f0, q = 1 }: NoiseOpts) {
  const src = ctx.createBufferSource();
  src.buffer = noise(ctx);
  const f = biquad(ctx);
  f.type = filter;
  f.Q.value = q;
  f.frequency.setValueAtTime(f0, t);
  if (f1 !== f0) f.frequency.exponentialRampToValueAtTime(f1, t + dur);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(gain, t + 0.004);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  src.connect(f).connect(g).connect(out);
  src.start(t, Math.random() * 0.5);
  src.stop(t + dur + 0.02);
}

const arp = (ctx: AudioContext, out: AudioNode, t: number, notes: number[], gap: number, o: Omit<ToneOpts, "f0">) =>
  notes.forEach((f, i) => tone(ctx, out, t + i * gap, { ...o, f0: f }));

const shimmer = (ctx: AudioContext, out: AudioNode, t: number, dur = 0.5) =>
  hiss(ctx, out, t, { dur, gain: 0.025, filter: "highpass", f0: 6000, f1: 9000 });

/** Each sound: schedules its voices and returns its length in seconds. */
const SOUNDS: Record<SfxName, (ctx: AudioContext, out: AudioNode, t: number) => number> = {
  click(c, o, t) {
    tone(c, o, t, { type: "square", f0: 2300, f1: 1400, dur: 0.025, gain: 0.045, lp: 5000 });
    hiss(c, o, t, { dur: 0.012, gain: 0.04, filter: "highpass", f0: 4000 });
    return 0.05;
  },
  tap(c, o, t) {
    tone(c, o, t, { type: "triangle", f0: 880, f1: 1320, dur: 0.05, gain: 0.07 });
    return 0.06;
  },
  toggleOn(c, o, t) {
    tone(c, o, t, { type: "square", f0: 520, dur: 0.04, gain: 0.04, lp: 3000 });
    tone(c, o, t + 0.05, { type: "square", f0: 780, dur: 0.06, gain: 0.04, lp: 3000 });
    return 0.12;
  },
  toggleOff(c, o, t) {
    tone(c, o, t, { type: "square", f0: 780, dur: 0.04, gain: 0.04, lp: 3000 });
    tone(c, o, t + 0.05, { type: "square", f0: 480, dur: 0.06, gain: 0.04, lp: 3000 });
    return 0.12;
  },
  open(c, o, t) {
    hiss(c, o, t, { dur: 0.16, gain: 0.08, f0: 300, f1: 3200, q: 2 });
    tone(c, o, t, { f0: 180, f1: 720, dur: 0.18, gain: 0.07 });
    tone(c, o, t + 0.16, { type: "square", f0: 1440, dur: 0.03, gain: 0.03, lp: 4000 });
    return 0.22;
  },
  close(c, o, t) {
    hiss(c, o, t, { dur: 0.14, gain: 0.07, f0: 3200, f1: 300, q: 2 });
    tone(c, o, t, { f0: 720, f1: 150, dur: 0.16, gain: 0.06 });
    return 0.18;
  },
  key(c, o, t) {
    hiss(c, o, t, { dur: 0.016, gain: 0.05, filter: "highpass", f0: 2800 + Math.random() * 1200 });
    tone(c, o, t, { type: "square", f0: 1700 + Math.random() * 500, dur: 0.012, gain: 0.015, lp: 4000 });
    return 0.03;
  },
  success(c, o, t) {
    arp(c, o, t, [784, 988, 1319], 0.06, { type: "triangle", dur: 0.16, gain: 0.08 });
    return 0.32;
  },
  error(c, o, t) {
    tone(c, o, t, { type: "square", f0: 160, dur: 0.09, gain: 0.06, lp: 1100 });
    tone(c, o, t + 0.11, { type: "square", f0: 150, dur: 0.12, gain: 0.06, lp: 1100 });
    return 0.25;
  },
  toast(c, o, t) {
    tone(c, o, t, { f0: 1320, dur: 0.2, gain: 0.06 });
    tone(c, o, t + 0.07, { f0: 1760, dur: 0.24, gain: 0.045 });
    return 0.32;
  },
  glitch(c, o, t) {
    for (let i = 0; i < 10; i++) tone(c, o, t + i * 0.028, { type: "square", f0: 80 + Math.random() * 1900, dur: 0.025, gain: 0.045, lp: 3500 });
    hiss(c, o, t, { dur: 0.32, gain: 0.07, filter: "lowpass", f0: 1800 });
    return 0.34;
  },
  hit(c, o, t) {
    tone(c, o, t, { type: "triangle", f0: 660, f1: 990, dur: 0.08, gain: 0.09 });
    return 0.1;
  },
  miss(c, o, t) {
    tone(c, o, t, { type: "square", f0: 220, f1: 140, dur: 0.14, gain: 0.05, lp: 900 });
    return 0.16;
  },
  win(c, o, t) {
    arp(c, o, t, [523, 659, 784, 1047], 0.07, { type: "triangle", dur: 0.2, gain: 0.08 });
    shimmer(c, o, t + 0.2);
    return 0.6;
  },
  lose(c, o, t) {
    tone(c, o, t, { type: "sawtooth", f0: 330, f1: 110, dur: 0.42, gain: 0.05, lp: 900 });
    return 0.45;
  },
  step(c, o, t) {
    tone(c, o, t, { f0: 1200, dur: 0.02, gain: 0.025 });
    return 0.03;
  },
  bronze(c, o, t) {
    arp(c, o, t, [523, 659, 784], 0.08, { type: "triangle", dur: 0.22, gain: 0.08 });
    return 0.45;
  },
  silver(c, o, t) {
    arp(c, o, t, [587, 740, 880, 1175], 0.075, { type: "triangle", dur: 0.24, gain: 0.08 });
    return 0.55;
  },
  gold(c, o, t) {
    arp(c, o, t, [659, 831, 988, 1319], 0.075, { type: "triangle", dur: 0.26, gain: 0.08 });
    tone(c, o, t + 0.3, { f0: 2637, dur: 0.5, gain: 0.03 });
    return 0.8;
  },
  platinum(c, o, t) {
    arp(c, o, t, [698, 880, 1047, 1397, 1760], 0.07, { type: "triangle", dur: 0.26, gain: 0.075 });
    shimmer(c, o, t + 0.25, 0.5);
    return 0.85;
  },
  diamond(c, o, t) {
    arp(c, o, t, [784, 988, 1175, 1568, 1976, 2349], 0.065, { type: "triangle", dur: 0.28, gain: 0.07 });
    shimmer(c, o, t + 0.25, 0.6);
    tone(c, o, t + 0.42, { f0: 3136, dur: 0.6, gain: 0.025 });
    return 1;
  },
  master(c, o, t) {
    [392, 494, 587, 784].forEach((f) => tone(c, o, t, { type: "sawtooth", f0: f, dur: 0.9, gain: 0.025, lp: 2400, attack: 0.04 }));
    arp(c, o, t + 0.1, [784, 988, 1175, 1568, 1976, 2349], 0.06, { type: "triangle", dur: 0.3, gain: 0.07 });
    shimmer(c, o, t + 0.4, 0.7);
    return 1.2;
  },
  rankup(c, o, t) {
    arp(c, o, t, [523, 523, 784, 1047], 0.1, { type: "square", dur: 0.16, gain: 0.04, lp: 3200 });
    tone(c, o, t + 0.4, { type: "triangle", f0: 1047, dur: 0.5, gain: 0.08 });
    shimmer(c, o, t + 0.4, 0.6);
    return 0.95;
  },
};

export function play(name: SfxName) {
  if (!level()) return;
  const now = performance.now();
  if (now - (lastPlayed.get(name) ?? -1e9) < 30) return;
  lastPlayed.set(name, now);

  const { ctx, sfx } = getMixer();
  wire();
  if (ctx.state === "suspended") void ctx.resume().catch(() => undefined);

  // Voice stealing: fade the oldest out when too many are ringing.
  const t = ctx.currentTime + 0.005;
  for (let i = voices.length - 1; i >= 0; i--) if (voices[i].end < t) voices.splice(i, 1);
  while (voices.length >= MAX_VOICES) {
    const old = voices.shift()!;
    old.out.gain.setTargetAtTime(0, t, 0.01);
  }

  const out = ctx.createGain();
  out.connect(sfx);
  const len = SOUNDS[name](ctx, out, t);
  voices.push({ out, end: t + len });
  setTimeout(() => out.disconnect(), (len + 0.3) * 1000);
  if (!NO_DUCK.has(name)) duck(name === "master" || name === "rankup" ? 0.45 : 0.6, Math.max(0.3, len));
}
