import type { Certification } from "./types";

/**
 * Certifications listed on LinkedIn (49). The owner holds more than are
 * listed publicly; the headline figure comes from profile.claims.
 */
export const certifications: Certification[] = [
  { name: "Generative AI", issuer: "Udacity", date: "2024-11", highlight: true, tags: ["ai"] },
  { name: "AI Engineer Certificate", issuer: "Pro5.ai", date: "2024-07", highlight: true, tags: ["ai"] },
  { name: "MongoDB Python Developer Path", issuer: "MongoDB", date: "2024-07", highlight: true, tags: ["data"] },
  { name: "Software Engineer Intern", issuer: "HackerRank", date: "2024-04", highlight: true, tags: ["career"] },
  { name: "Foundational C# with Microsoft", issuer: "freeCodeCamp", date: "2023-10", tags: ["lang"] },
  { name: "Responsive Web Design", issuer: "freeCodeCamp", date: "2023-07", tags: ["web"] },
  { name: "Machine Learning with Python", issuer: "freeCodeCamp", date: "2023-07", highlight: true, tags: ["ai"] },
  { name: "JavaScript Algorithms and Data Structures", issuer: "freeCodeCamp", date: "2023-06", tags: ["lang"] },
  { name: "Angular + NestJS", issuer: "Sololearn", date: "2023-02", tags: ["web"] },
  { name: "Introduction to Python", issuer: "Global AI Hub", date: "2022-09", tags: ["lang"] },
  { name: "Game Development with JS", issuer: "Sololearn", date: "2022-08", tags: ["web"] },
  { name: "Go", issuer: "Sololearn", date: "2022-08", tags: ["lang"] },
  { name: "R", issuer: "Sololearn", date: "2022-07", tags: ["lang"] },
  { name: "Machine Learning", issuer: "Sololearn", date: "2022-07", tags: ["ai"] },
  { name: "Kotlin", issuer: "Sololearn", date: "2022-07", tags: ["lang"] },
  { name: "jQuery", issuer: "Sololearn", date: "2022-07", tags: ["web"] },
  { name: "Machine Learning and Image Processing", issuer: "Cisco", date: "2021-12", highlight: true, tags: ["ai"] },
  { name: "AWS Computer Vision: Getting Started with GluonCV", issuer: "AWS · Coursera", date: "2020-08", highlight: true, tags: ["ai", "cloud"] },
  { name: "COVID-19 Contact Tracing", issuer: "Coursera", date: "2020-08", tags: ["career"] },
  { name: "Introduction to Programming with MATLAB", issuer: "Coursera", date: "2020-08", tags: ["lang"] },
  { name: "Google Cloud Platform Fundamentals for AWS Professionals", issuer: "Google Cloud · Coursera", date: "2020-08", highlight: true, tags: ["cloud"] },
  { name: "Building Conversational Experiences with Dialogflow", issuer: "Google Cloud · Coursera", date: "2020-08", tags: ["ai", "cloud"] },
  { name: "Introduction to Cloud Identity", issuer: "Google Cloud · Coursera", date: "2020-08", tags: ["cloud"] },
  { name: "How to Write a Resume", issuer: "Coursera", date: "2020-07", tags: ["career"] },
  { name: "Developing AI Applications on Azure", issuer: "Coursera", date: "2020-07", highlight: true, tags: ["ai", "cloud"] },
  { name: "Industrial IoT on Google Cloud Platform", issuer: "Google Cloud · Coursera", date: "2020-07", highlight: true, tags: ["cloud"] },
  { name: "Microsoft Certified: Data Analyst Associate (Power BI)", issuer: "Udemy", date: "2020-07", highlight: true, tags: ["data"] },
  { name: "Cloud Computing Basics (Cloud 101)", issuer: "Coursera", date: "2020-07", tags: ["cloud"] },
  { name: "Getting Started with AWS Machine Learning", issuer: "AWS · Coursera", date: "2020-07", highlight: true, tags: ["ai", "cloud"] },
  { name: "Code Yourself! An Introduction to Programming", issuer: "Coursera", date: "2020-07", tags: ["lang"] },
  { name: "Introduction to Flutter Development Using Dart", issuer: "The App Brewery", date: "2020-06", tags: ["mobile"] },
  { name: "Swift 4 Fundamentals", issuer: "Sololearn", date: "2020-06", tags: ["lang"] },
  { name: "Ruby", issuer: "Sololearn", date: "2020-06", tags: ["lang"] },
  { name: "Build Your First Android App", issuer: "Coursera", date: "2020-06", tags: ["mobile"] },
  { name: "React + Redux", issuer: "Sololearn", date: "2020-06", tags: ["web"] },
  { name: "Python 3", issuer: "Sololearn", date: "2020-05", tags: ["lang"] },
  { name: "CSS Fundamentals", issuer: "Sololearn", date: "2020-05", tags: ["web"] },
  { name: "C#", issuer: "Sololearn", date: "2020-05", tags: ["lang"] },
  { name: "PHP", issuer: "Sololearn", date: "2020-05", tags: ["lang"] },
  { name: "C", issuer: "Sololearn", date: "2020-05", tags: ["lang"] },
  { name: "Google Ads Display Certification", issuer: "Google", date: "2020-05", expired: true, tags: ["marketing"] },
  { name: "Google My Business Basics", issuer: "Google", date: "2020-05", tags: ["marketing"] },
  { name: "The Fundamentals of Digital Marketing", issuer: "Google", date: "2020-05", tags: ["marketing"] },
  { name: "Basics of Java", issuer: "Amity Future Academy", date: "2020-05", tags: ["lang"] },
  { name: "C++", issuer: "Sololearn", date: "2019-11", tags: ["lang"] },
  { name: "JavaScript", issuer: "Sololearn", date: "2019-08", tags: ["lang"] },
  { name: "SQL Fundamentals", issuer: "Sololearn", date: "2017-10", tags: ["data"] },
  { name: "Java", issuer: "Sololearn", date: "2017-09", tags: ["lang"] },
  { name: "HTML Fundamentals", issuer: "Sololearn", date: "2017-09", tags: ["web"] },
];
