import type { Project, RepoOverride } from "./types";

/**
 * Curated projects. Anything with `repo` is enriched with live GitHub data
 * (stars, forks, languages, last push) by src/lib/projects.ts. Public repos
 * not listed here still appear automatically after the monthly sync, using
 * their README summary; tune them via `repoOverrides` below.
 */
export const projects: Project[] = [
  // ── Minion Technologies ────────────────────────────────────────────────
  {
    slug: "zoyemed",
    title: "ZoyeMed",
    tagline: "Autonomous medical kiosk & healthcare AI platform",
    description:
      "ZoyeMed integrates AI, multimodal medical analysis, edge computing, telemedicine, computer vision and diagnostic devices into one clinical system, deployed across international markets on both on-device inference and Scaleway cloud. I build its production AI: clinical decision support, conversational healthcare, medical-data processing, computer vision and edge/on-prem LLM inference.",
    highlights: [
      "Local LLM inference with MedGemma, Qwen, GPT-OSS and DeepSeek R1 via llama.cpp and vLLM; MedGemma-27B-IT quantized to MXFP4 on NVIDIA Blackwell and ROCm hardware.",
      "Real-time voice and text conversational AI with multimodal reasoning and tool calling for Doctor, Nurse and Patient roles.",
      "RAG over OpenFDA and ICD-11 with 30% better retrieval latency and performance.",
      "LOINC mapping, multilingual medical-data processing and medicine matching.",
      "Ubuntu kiosk enforcement, hardware validation and Bluetooth/USB device integration.",
    ],
    roleId: "minion",
    start: "2025-06",
    end: null,
    tech: ["PyTorch", "MedGemma", "Qwen", "GPT-OSS", "llama.cpp", "vLLM", "ROCm", "LoRA/QLoRA", "Unsloth", "RAG", "Docker", "Electron", "Scaleway"],
    categories: ["ai", "llm", "agents", "cv"],
    links: {},
    featured: true,
    status: "active",
    metrics: [
      { label: "Deployment", value: "International" },
      { label: "RAG gain", value: "+30%" },
      { label: "Quantization", value: "MXFP4" },
    ],
  },
  {
    slug: "phi-deidentification-pipeline",
    title: "Clinical De-identification Pipeline",
    tagline: "Hospital archives → MedGemma training corpora, on-prem",
    description:
      "An on-premise pipeline that turns unstructured hospital archives into MedGemma training data without a single identifier leaving the building. Provider-agnostic multimodal page reading (Anthropic API, any OpenAI-compatible endpoint, or self-hosted vLLM), clinical/non-clinical classification, PHI removal from transcribed text and scanned images, automated leak verification, and AES-256 per-location packaging with SHA-256 manifests.",
    highlights: [
      "Image PHI removed with fractional rotated zonal masking; zero surviving identifiers on a 48-page clinical validation sample.",
      "Data-driven redaction entities generated from extractor-reported PHI, eliminating O(patients × pages) matching at multi-terabyte scale.",
      "In-place ZIP reading with header-only content sniffing surveyed an 11,631-file archive ~20× faster than full decompression.",
      "Batched, checkpointed stages that resume after interruption.",
      "Hardware and cost analysis (memory bandwidth, dense vs. MoE, per-page token economics) behind the on-prem decision.",
    ],
    roleId: "minion",
    start: "2025-06",
    end: null,
    tech: ["Python", "vLLM", "Anthropic API", "OpenAI-compatible APIs", "OCR", "AES-256", "MedGemma"],
    categories: ["ai", "llm", "cv"],
    links: {},
    featured: true,
    status: "active",
    metrics: [
      { label: "Leaked identifiers", value: "0" },
      { label: "Archive survey", value: "~20× faster" },
      { label: "Files surveyed", value: "11,631" },
    ],
  },
  {
    slug: "agentic-crm-automation",
    title: "Agentic CRM Automation",
    tagline: "Autonomous lead discovery, scoring and outreach",
    description:
      "Agentic AI workflows covering lead discovery, lead scoring, organizational research, personalized email generation and SEO/marketing content generation for ZoyeMed's go-to-market.",
    roleId: "minion",
    start: "2025-06",
    end: null,
    tech: ["LLM agents", "Tool calling", "Python", "Prompt engineering"],
    categories: ["agents", "llm"],
    links: {},
    status: "active",
  },
  {
    slug: "ptz-face-tracking",
    title: "PTZ Face Detection & Tracking",
    tagline: "Camera control for automated patient examination",
    description:
      "Computer-vision system driving PTZ cameras for face detection and tracking, enabling automated patient identification and examination workflows on the ZoyeMed kiosk.",
    roleId: "minion",
    start: "2025-06",
    end: null,
    tech: ["OpenCV", "Python", "Computer Vision", "PTZ control"],
    categories: ["cv", "ai", "iot"],
    links: {},
    status: "active",
  },

  // ── PTS Consulting Services ───────────────────────────────────────────
  {
    slug: "koyox",
    title: "KoyoX",
    tagline: "Custom GPT job assistant with voice and avatar",
    description:
      "A full-stack, Flask-based GPT-4 job assistant with text and voice chat and an interactive avatar, built on OpenAI's Assistants API with a custom knowledge base. Shipped to production within a month of the Assistants API release; KoyoX Beta was also integrated into the company's careers site.",
    highlights: [
      "Custom knowledge base improved data-retrieval efficiency by 30%.",
      "Text + voice chat and an animated avatar.",
      "Careers-site integration in PHP/MySQL.",
    ],
    roleId: "pts",
    start: "2023-10",
    end: "2024-01",
    tech: ["Python", "Flask", "OpenAI Assistants API", "GPT-4", "PHP", "MySQL", "Azure"],
    categories: ["ai", "llm", "web"],
    links: { live: "https://koyoxai.azurewebsites.net/", repo: "https://github.com/AvishakeAdhikary/AI-Job-Assistant-ChatApp" },
    image: "projects/KoyoX.png",
    repo: "AI-Job-Assistant-ChatApp",
    featured: true,
    status: "shipped",
  },
  {
    slug: "yujj",
    title: "Yujj",
    tagline: "Okta SSO with NFC-card and QR login",
    description:
      "Led the design and implementation of Single Sign-On for Yujj, integrating Okta for authentication and authorization, with NFC-card and QR-code redirection flows for a secure, frictionless login.",
    roleId: "pts",
    start: "2023-09",
    end: "2024-01",
    tech: ["Okta", "SSO", "NFC", "QR", "Java", "Android"],
    categories: ["web", "mobile"],
    links: { live: "https://www.yujj.ai/" },
    image: "projects/Yujj.png",
    status: "shipped",
  },
  {
    slug: "smart-document-processing",
    title: "Smart Document Processing",
    tagline: "VGG16 document comparison (SDP/IDP)",
    description:
      "A VGG16 model comparing documents through vectorized image data for PTS's Smart/Intelligent Document Processing product, improving comparison accuracy by 15%.",
    roleId: "pts",
    start: "2023-09",
    end: "2024-01",
    tech: ["TensorFlow", "VGG16", "Python", "Computer Vision"],
    categories: ["ai", "cv"],
    links: {},
    status: "shipped",
    metrics: [{ label: "Accuracy", value: "+15%" }],
  },
  {
    slug: "digitys-gpt",
    title: "DIGITYS GPT",
    tagline: "Internal GPT workspace for employees",
    description:
      "An internal interface giving employees GPT capabilities without the OpenAI portal, plus Bitbucket CI/CD pipelines deploying Docker containers to Azure.",
    roleId: "pts",
    start: "2023-12",
    end: "2024-01",
    tech: ["OpenAI API", "React", "Docker", "Azure", "Bitbucket CI/CD"],
    categories: ["llm", "web"],
    links: {},
    status: "shipped",
  },

  // ── Travarsa ──────────────────────────────────────────────────────────
  {
    slug: "medifitserve",
    title: "MediFitServe",
    tagline: "Full-stack WordPress health-services site",
    description:
      "A full-stack WordPress website with custom pop-ups, responsive design and file uploads; SEO/SEM work grew traffic by 40%.",
    roleId: "travarsa-2022",
    start: "2022-07",
    end: "2022-08",
    tech: ["WordPress", "PHP", "SEO"],
    categories: ["web"],
    links: {},
    status: "shipped",
    metrics: [{ label: "Traffic", value: "+40%" }],
  },
  {
    slug: "guide-me-wide",
    title: "Guide Me Wide",
    tagline: "Full-stack WordPress travel site + campaigns",
    description:
      "A user-centric WordPress site with dynamic pop-ups and file uploads, plus digital-marketing campaigns that lifted search rankings by 50%.",
    roleId: "travarsa-2020",
    start: "2020-04",
    end: "2020-06",
    tech: ["WordPress", "PHP", "Digital Marketing"],
    categories: ["web"],
    links: {},
    status: "shipped",
    metrics: [{ label: "Search ranking", value: "+50%" }],
  },

  // ── Independent ───────────────────────────────────────────────────────
  {
    slug: "realtime-sign-language-detection",
    title: "Realtime Sign Language Detection",
    tagline: "Real-time LSTM gesture recognition from a webcam",
    description:
      "A real-time sign-language recognition system: OpenCV video capture feeding an LSTM network in TensorFlow, covering data collection, training and evaluation, with support for adding and training new gestures. Built as assistive technology to help people with hearing impairments communicate.",
    start: "2023-05",
    end: "2025-11",
    tech: ["Python", "TensorFlow", "LSTM", "OpenCV", "NumPy"],
    categories: ["ai", "cv"],
    links: { repo: "https://github.com/AvishakeAdhikary/Realtime-Sign-Language-Detection-Using-LSTM-Model" },
    image: "projects/rtsldlm.png",
    repo: "Realtime-Sign-Language-Detection-Using-LSTM-Model",
    featured: true,
    status: "shipped",
  },
  {
    slug: "nexcpp",
    title: "nexcpp",
    tagline: "MCP server giving AI agents deep C++ expertise",
    description:
      "A Model Context Protocol server that gives Claude, Codex, Cursor and Windsurf structured knowledge of C++ development: language and library docs, CMake, vcpkg/Conan, sandboxed builds, static analysis, code generation and GitHub automation, over JSON-RPC stdio or SSE.",
    start: "2026-05",
    tech: ["Python", "MCP", "JSON-RPC", "CMake", "Clang tooling"],
    categories: ["agents", "llm", "systems"],
    links: { repo: "https://github.com/AvishakeAdhikary/nexcpp" },
    repo: "nexcpp",
    featured: true,
    status: "active",
  },
  {
    slug: "nexscout",
    title: "NexScout",
    tagline: "Always-on autonomous job-application agent",
    description:
      "An autonomous agent that discovers jobs, scores them against a profile, tailors a LaTeX resume and cover letter per application, and applies via browser automation in a crash-resilient autopilot loop. The whole pipeline is also exposed as an MCP server, and every LLM prompt is spec-locked by tests.",
    start: "2026-05",
    end: "2026-06",
    tech: ["Python", "LLM agents", "MCP", "LaTeX", "Browser automation", "Tailwind"],
    categories: ["agents", "llm"],
    links: { repo: "https://github.com/AvishakeAdhikary/NexScout" },
    repo: "NexScout",
    featured: true,
    status: "active",
  },
  {
    slug: "solidworks-mcp-server",
    title: "SolidWorks MCP Server",
    tagline: "41 CAD tools for AI agents, pure Python COM",
    description:
      "Drives SolidWorks 2018–2026 from any MCP client through its COM API: 41 tools across parts, assemblies, drawings, sheet metal, analysis and export. Every COM call is marshalled onto one STA thread and API signature churn is resolved at runtime, unlocking advanced APIs that silently fail from MTA callers, without compiled interop assemblies.",
    start: "2026-08",
    tech: ["Python", "MCP", "COM", "win32com", "SolidWorks API"],
    categories: ["agents", "systems"],
    links: { repo: "https://github.com/AvishakeAdhikary/solidworks-mcp-server" },
    repo: "solidworks-mcp-server",
    featured: true,
    status: "active",
    metrics: [{ label: "Tools", value: "41" }, { label: "Versions", value: "2018–2026" }],
  },
  {
    slug: "nexremote",
    title: "NexRemote",
    tagline: "Your Windows PC, from your Android phone",
    description:
      "Open-source remote control for Windows: screen sharing with PC audio, a wireless gamepad (xinput/dinput, gyro, macros), keyboard and mouse, webcams, file explorer, media control and task manager. A native WinUI 3/.NET 8 host (on the Microsoft Store) with a secure WebSocket server and UDP discovery, and a Kotlin/Jetpack Compose client with QR, LAN and USB pairing.",
    start: "2026-01",
    tech: ["C#", ".NET 8", "WinUI 3", "Kotlin", "Jetpack Compose", "WebSockets"],
    categories: ["desktop", "mobile", "systems"],
    links: { repo: "https://github.com/AvishakeAdhikary/NexRemote", live: "https://avishakeadhikary.github.io/NexRemote/" },
    repo: "NexRemote",
    featured: true,
    status: "active",
  },
  {
    slug: "tone-sphere",
    title: "Tone Sphere",
    tagline: "Low-latency audio routing, mixing & VST3 hosting",
    description:
      "A real-time C++ audio engine behind a C ABI with WASAPI and ASIO backends and a VST3 host, driven by a Python control plane; Linux and macOS run the same app on PortAudio. Built because a guitarist shouldn't have to pay twice to hear their own instrument.",
    start: "2025-09",
    tech: ["C++", "Python", "WASAPI", "ASIO", "VST3", "PortAudio"],
    categories: ["desktop", "systems"],
    links: { repo: "https://github.com/AvishakeAdhikary/tone-sphere", live: "https://avishakeadhikary.github.io/tone-sphere/" },
    repo: "tone-sphere",
    featured: true,
    status: "active",
  },
  {
    slug: "nexcode",
    title: "NexCode",
    tagline: "Native Windows agentic AI coding platform",
    description:
      "A native Windows agentic coding platform built with WinUI 3 and a CLI-first execution model, with Microsoft Store subscriptions, encrypted local state and opt-in telemetry.",
    start: "2026-04",
    tech: ["C#", "WinUI 3", "LLM agents", "SQLite"],
    categories: ["agents", "desktop"],
    links: { repo: "https://github.com/AvishakeAdhikary/NexCode", docs: "https://avishakeadhikary.github.io/NexCode/" },
    repo: "NexCode",
    status: "wip",
  },
  {
    slug: "nexguild",
    title: "NexGuild",
    tagline: "No-code Discord bots on a visual node graph",
    description:
      "A Windows desktop app for hosting Discord bots locally where every behavior (commands, moderation, music, AI agents with bring-your-own OpenAI/Google/Anthropic keys) is built on a visual trigger → condition → action node graph with its own templating language.",
    start: "2026-05",
    tech: ["C#", "WinUI 3", "Discord API", "Node graphs", "LLM providers"],
    categories: ["desktop", "agents"],
    links: { repo: "https://github.com/AvishakeAdhikary/NexGuild", live: "https://avishakeadhikary.github.io/NexGuild/" },
    repo: "NexGuild",
    status: "wip",
  },
  {
    slug: "echoflow",
    title: "EchoFlow",
    tagline: "Voice-to-voice AI over WebSockets",
    description:
      "A voice-to-voice AI system with a WebSocket server and GUI client: Whisper speech-to-text, Kokoro text-to-speech, MCP tool calls, SQLite session persistence and any OpenAI-compatible model endpoint.",
    start: "2025-08",
    end: "2025-08",
    tech: ["Python", "Whisper", "Kokoro TTS", "WebSockets", "MCP", "SQLite"],
    categories: ["ai", "llm", "agents"],
    links: { repo: "https://github.com/AvishakeAdhikary/EchoFlow" },
    repo: "EchoFlow",
    status: "shipped",
  },
  {
    slug: "echosight",
    title: "EchoSight",
    tagline: "Streaming multimodal assistant: camera, voice, chat",
    description:
      "A FastAPI server streaming audio and camera frames to a multimodal model and returning low-latency speech and text, with Silero VAD preprocessing and SSE/WebSocket endpoints.",
    start: "2025-08",
    end: "2025-08",
    tech: ["Python", "FastAPI", "Transformers", "Silero VAD", "ONNX", "WebSockets"],
    categories: ["ai", "llm", "cv"],
    links: { repo: "https://github.com/AvishakeAdhikary/EchoSight" },
    repo: "EchoSight",
    status: "shipped",
  },
  {
    slug: "neural-networks-from-scratch",
    title: "Neural Networks From Scratch",
    tagline: "From derivatives to a GPT, one notebook at a time",
    description:
      "A lecture series of Jupyter notebooks building neural networks from first principles: derivative-based fundamentals, the NameWeave bigram → MLP progression, activations/gradients/batch-norm, manual backpropagation, a WaveNet-style CNN, and finally a decoder-only GPT with self-attention.",
    start: "2024-01",
    end: "2024-05",
    tech: ["Python", "PyTorch", "Jupyter", "Transformers"],
    categories: ["ai", "llm"],
    links: { repo: "https://github.com/AvishakeAdhikary/Neural-Networks-From-Scratch" },
    image: "projects/NNFS_GitHub_Banner.gif",
    repo: "Neural-Networks-From-Scratch",
    featured: true,
    status: "shipped",
  },
  {
    slug: "text-to-image-generator",
    title: "Text-to-Image Generator",
    tagline: "Stable Diffusion desktop app",
    description:
      "A GUI application generating images from text prompts with the Stable Diffusion pipeline (PyTorch, diffusers, Hugging Face).",
    start: "2023-05",
    end: "2023-07",
    tech: ["Python", "PyTorch", "Stable Diffusion", "Hugging Face", "CustomTkinter"],
    categories: ["ai"],
    links: { repo: "https://github.com/AvishakeAdhikary/Text-To-Image-Generator" },
    image: "projects/texttoimage.jpg",
    repo: "Text-To-Image-Generator",
    status: "shipped",
  },
  {
    slug: "python-code-generator",
    title: "Python Code Generator",
    tagline: "Code generation with Salesforce CodeGPT",
    description:
      "Generates code snippets from prompts with Salesforce's pre-trained CodeGPT model via Hugging Face Transformers.",
    start: "2023-05",
    end: "2023-06",
    tech: ["Python", "Hugging Face Transformers", "CodeGPT"],
    categories: ["ai", "llm"],
    links: { repo: "https://github.com/AvishakeAdhikary/Python-Code-Generator" },
    image: "projects/pcg.png",
    repo: "Python-Code-Generator",
    status: "shipped",
  },
  {
    slug: "face-recognition-flutter",
    title: "Face Recognition Flutter",
    tagline: "On-device MobileFaceNet with TFLite",
    description:
      "Real-time on-device face recognition in Flutter using a pre-trained MobileFaceNet and TensorFlow Lite with GPU delegates.",
    start: "2021-02",
    end: "2023-05",
    tech: ["Flutter", "Dart", "TensorFlow Lite", "MobileFaceNet"],
    categories: ["ai", "cv", "mobile"],
    links: { repo: "https://github.com/AvishakeAdhikary/FaceRecognitionFlutter" },
    image: "projects/frf.png",
    video: "projects/frf.mp4",
    repo: "FaceRecognitionFlutter",
    status: "shipped",
  },
  {
    slug: "realtime-sign-language-detection-react",
    title: "Sign Language Detection (Web)",
    tagline: "In-browser TensorFlow.js object detection",
    description:
      "A React application detecting signs in real time in the browser with a TensorFlow object-detection model.",
    start: "2023-05",
    end: "2023-05",
    tech: ["React", "TensorFlow.js", "Object detection"],
    categories: ["ai", "cv", "web"],
    links: { repo: "https://github.com/AvishakeAdhikary/Realtime-Sign-Language-Detection-Using-React.js" },
    image: "projects/rtsldr.png",
    repo: "Realtime-Sign-Language-Detection-Using-React.js",
    status: "shipped",
  },
  {
    slug: "meditourself",
    title: "MedItYourself",
    tagline: "Native Android health app for users and providers",
    description:
      "A native Android health app with user and provider sides: Firebase Auth/Database/Storage, Google Maps, Directions and Places, Camera2 and Glide, with multithreaded networking.",
    start: "2020-07",
    end: "2020-07",
    tech: ["Java", "Android", "Firebase", "Google Maps API"],
    categories: ["mobile"],
    links: { repo: "https://github.com/AvishakeAdhikary/MedItYourself" },
    image: "projects/medityourself.jpg",
    repo: "MedItYourself",
    status: "shipped",
  },
  {
    slug: "health-application",
    title: "Health Application",
    tagline: "React health predictor (diabetes, BMI)",
    description:
      "A web application predicting health indicators such as diabetes risk and BMI from basic inputs, built with React and its own back end during the BCA at Amity.",
    roleId: "amity-bca",
    start: "2018-11",
    end: "2019-11",
    tech: ["React", "JavaScript", "CSS"],
    categories: ["web"],
    links: { repo: "https://github.com/AvishakeAdhikary/HealthApp", live: "https://avishakeadhikary.github.io/HealthApp/" },
    image: "projects/HealthApp.png",
    repo: "HealthApp",
    status: "shipped",
  },
  {
    slug: "radxa-home-assistant",
    title: "Radxa Zero 3E Home Assistant Appliance",
    tagline: "Desktop image → headless HA Supervised appliance",
    description:
      "Transforms the vendor Debian 12 image into a minimal headless Home Assistant Supervised appliance: ~1,170 packages removed (5.4 GB → 2.3 GB) while preserving full board support, validated on real hardware.",
    start: "2026-07",
    tech: ["Linux", "Debian", "Docker", "Home Assistant", "Bash"],
    categories: ["iot", "systems"],
    links: { repo: "https://github.com/AvishakeAdhikary/RadxaZero3EHomeAssistant" },
    repo: "RadxaZero3EHomeAssistant",
    status: "shipped",
  },
  {
    slug: "os-portfolio",
    title: "OS Portfolio",
    tagline: "A portfolio that boots like a desktop OS",
    description:
      "An interactive desktop-OS-style portfolio template in Vue.js with a boot sequence, lock screen, windows and apps.",
    start: "2023-06",
    tech: ["Vue.js", "JavaScript", "CSS"],
    categories: ["web"],
    links: { repo: "https://github.com/AvishakeAdhikary/OS-Portfolio", live: "https://avishakeadhikary.github.io/OS-Portfolio/" },
    image: "projects/osportfolio.png",
    video: "projects/osportfolio.mp4",
    repo: "OS-Portfolio",
    status: "active",
  },
  {
    slug: "3d-portfolio",
    title: "3D Portfolio",
    tagline: "Open-world portfolio in Three.js",
    description: "An interactive open-world portfolio built with vanilla JavaScript and Three.js.",
    start: "2022-08",
    tech: ["Three.js", "JavaScript", "WebGL"],
    categories: ["web"],
    links: { repo: "https://github.com/AvishakeAdhikary/3D-Portfolio", live: "https://avishakeadhikary.github.io/3D-Portfolio/" },
    image: "projects/3dportfolio.png",
    video: "projects/3dportfolio.mp4",
    repo: "3D-Portfolio",
    status: "active",
  },
];

/**
 * Curation for repos that come in via the GitHub sync. Repos not mentioned
 * here and not linked from `projects` are shown in the "More on GitHub" list.
 */
export const repoOverrides: Record<string, RepoOverride> = {
  AvishakeAdhikary: { hide: true },
  "avishakeadhikary.github.io": { hide: true },
  "discord-bot-slash-commands-deleter": { categories: ["systems"] },
  "Suit-Up-Lounge": { title: "Suit-Up Lounge", tagline: "Discord community website", categories: ["web"] },
  "All-in-One-Discord-Python-BOT": { title: "All-in-One Discord Bot (Python)", categories: ["ai", "llm"] },
  "All-in-One-Discord-JavaScript-BOT": { title: "All-in-One Discord Bot (TypeScript)", categories: ["web"] },
  "Neural-Nexus-Studios": { title: "Neural Nexus Studios", tagline: "Studio website (Next.js)", categories: ["web"] },
  blog: { title: "monolog", tagline: "Monospace Markdown blog (Next.js)", categories: ["web"] },
  TensorC: { title: "TensorC", tagline: "Tensors in C (work in progress)", categories: ["systems"] },
  HomeAssistantPlayitGGCustom: { title: "Playit.gg Home Assistant Add-on", categories: ["iot"] },
  My_Flutter_Card: { title: "My Flutter Card", categories: ["mobile"], image: "projects/fluttercard.png" },
  FirstReactRobotGenerator: { title: "First React Robot Generator", categories: ["web"], image: "projects/firstreactrobotgenerator.png" },
};
