import type { Publication } from "./types";

/** Verified against Google Scholar (user 2fegUHYAAAAJ). Newest first. */
export const publications: Publication[] = [
  {
    title: "Quantum Computing for Cryptography: An Extensive Survey",
    authors: ["S. Debnath", "A. Adhikary"],
    selfIndex: 1,
    venue: "Edge of Intelligence: Exploring the Frontiers of AI at the Edge",
    publisher: "John Wiley & Sons (Scrivener Publishing)",
    pages: "327–350",
    date: "2025-04-14",
    doi: "10.1002/9781394314409.ch12",
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1002/9781394314409.ch12",
    kind: "Book chapter",
    scholarTitle: "Quantum Computing for Cryptography: An Extensive Survey",
  },
  {
    title:
      "Machine Learning (ML) and Blockchain for IoE: A Deep Insight into Framework, Security, and its Applications with Industrial IoE",
    authors: ["A. Adhikary", "S. Debnath", "D. Sarkar"],
    selfIndex: 0,
    venue: "Blockchain Technology for IoE: Security and Privacy Perspectives",
    publisher: "CRC Press (Taylor & Francis)",
    pages: "121",
    date: "2023-09-29",
    doi: "10.1201/9781003366010-8",
    url: "https://www.routledge.com/Blockchain-Technology-for-IoE-Security-and-Privacy-Perspectives/Solanki-Singh-Tanwar/p/book/9781032431741",
    kind: "Book chapter",
    scholarTitle:
      "Machine Learning (ML) and Blockchain for IoE: A Deep Insight into Framework, Security, and its Applications with Industrial IoE",
  },
  {
    title: "Design of an IoT-Based Mobile Healthcare Unit Using a Self-Regulated React.js Database and Arduino",
    authors: ["P. K. Dutta", "R. Karmakar", "R. Pipalwa", "A. Adhikary", "A. Chakraborty", "A. Pattnaik"],
    selfIndex: 3,
    venue: "Advances in Applications of Computational Intelligence and the Internet of Things",
    publisher: "Apple Academic Press",
    pages: "49–61",
    date: "2022-06-01",
    isbn: "9781771889698",
    url: "https://www.appleacademicpress.com/advances-in-applications-of-computational-intelligence-and-the-internet-of-things-iot-/9781771889698",
    kind: "Book chapter",
    scholarTitle: "Design of an IoT-Based Mobile Healthcare Unit Using a Self-regulated React. js Database and Arduino",
  },
  {
    title: "Deep Learning for COVID-19",
    authors: ["S. Dutta", "A. Adhikary", "D. Sarkar", "D. K. Kole", "P. Jana"],
    selfIndex: 1,
    venue: "Artificial Intelligence for COVID-19",
    publisher: "Springer International Publishing",
    pages: "551–565",
    date: "2021-07-20",
    doi: "10.1007/978-3-030-69744-0_30",
    url: "https://link.springer.com/chapter/10.1007/978-3-030-69744-0_30",
    kind: "Book chapter",
    scholarTitle: "Deep Learning for COVID-19",
  },
  {
    title: "Development of a Risk-Based Information Security Standard for Adaption of Blockchain-Enabled Systems",
    authors: ["A. Biswas", "A. Adhikary", "P. K. Dutta", "A. Chakroborty"],
    selfIndex: 1,
    venue: "International Conference on Mobile Computing and Sustainable Informatics (ICMCSI 2020)",
    publisher: "Springer International Publishing",
    pages: "619–631",
    date: "2020-01-23",
    doi: "10.1007/978-3-030-49795-8_59",
    url: "https://link.springer.com/chapter/10.1007/978-3-030-49795-8_59",
    kind: "Conference paper",
    scholarTitle: "Development of a risk-based information security standard for adaption of blockchain-enabled systems",
  },
];
