import type { SkillCategory } from "./types";

/**
 * Skills by category. `icon.si` is a simple-icons slug (rendered inline on the
 * server, zero client JS); `icon.svg` is a key into media-manifest svgs for
 * brands simple-icons no longer ships; `icon.glyph` is a lucide icon name.
 * `production: true` = used in shipped, professional work.
 * `verified: true` = passed the LinkedIn Skill Assessment.
 */
export const skillCategories: SkillCategory[] = [
  {
    id: "llm",
    title: "LLMs & Generative AI",
    blurb: "Fine-tuning, quantization and serving open-weight models on real hardware.",
    skills: [
      { name: "LoRA / QLoRA fine-tuning", icon: { glyph: "SlidersHorizontal" }, production: true },
      { name: "Unsloth", icon: { glyph: "Zap" }, production: true },
      { name: "llama.cpp / GGUF", icon: { glyph: "Cpu" }, production: true },
      { name: "MXFP4 quantization", icon: { glyph: "Binary" }, production: true },
      { name: "vLLM", icon: { glyph: "Server" }, production: true },
      { name: "Hugging Face", icon: { si: "huggingface" }, production: true },
      { name: "MedGemma · Gemma", icon: { si: "googlegemini" }, production: true },
      { name: "Qwen · DeepSeek R1 · GPT-OSS", icon: { glyph: "Brain" }, production: true },
      { name: "RAG", icon: { glyph: "DatabaseZap" }, production: true },
      { name: "Prompt engineering", icon: { glyph: "TerminalSquare" }, production: true },
      { name: "OpenAI API", icon: { glyph: "Sparkles" }, production: true },
      { name: "Anthropic API", icon: { si: "anthropic" }, production: true },
      { name: "Ollama", icon: { si: "ollama" } },
      { name: "Stable Diffusion", icon: { glyph: "Image" } },
      { name: "Whisper · Kokoro TTS", icon: { glyph: "AudioLines" } },
    ],
  },
  {
    id: "agents",
    title: "Agentic AI & MCP",
    blurb: "Tool-calling agents, Model Context Protocol servers and autonomous workflows.",
    skills: [
      { name: "Agentic workflow automation", icon: { glyph: "Workflow" }, production: true },
      { name: "Tool calling", icon: { glyph: "Wrench" }, production: true },
      { name: "Multimodal reasoning", icon: { glyph: "ScanEye" }, production: true },
      { name: "Model Context Protocol", icon: { si: "modelcontextprotocol" } },
      { name: "Claude Code · Codex", icon: { si: "claude" } },
      { name: "LangChain", icon: { si: "langchain" } },
      { name: "AI guardrails & PHI redaction", icon: { glyph: "ShieldCheck" }, production: true },
    ],
  },
  {
    id: "ml",
    title: "ML & Deep Learning",
    blurb: "From derivatives by hand to distributed multi-GPU training.",
    skills: [
      { name: "PyTorch", icon: { si: "pytorch" }, production: true },
      { name: "TensorFlow", icon: { si: "tensorflow" }, production: true },
      { name: "Keras", icon: { si: "keras" } },
      { name: "scikit-learn", icon: { si: "scikitlearn" } },
      { name: "Distributed training (DDP)", icon: { glyph: "Network" }, production: true },
      { name: "ROCm", icon: { si: "amd" }, production: true },
      { name: "CUDA / NVIDIA", icon: { si: "nvidia" }, production: true },
      { name: "ONNX Runtime", icon: { si: "onnx" } },
      { name: "Feature & data engineering", icon: { glyph: "Table2" }, production: true },
      { name: "Pandas", icon: { si: "pandas" } },
      { name: "NumPy", icon: { si: "numpy" } },
      { name: "Jupyter", icon: { si: "jupyter" } },
      { name: "Seaborn", icon: { svg: "skills/seaborn.svg" } },
    ],
  },
  {
    id: "cv",
    title: "Computer Vision",
    blurb: "Detection, tracking and recognition on cameras, kiosks and phones.",
    skills: [
      { name: "OpenCV", icon: { si: "opencv" }, production: true },
      { name: "Face detection & tracking (PTZ)", icon: { glyph: "ScanFace" }, production: true },
      { name: "Document AI · OCR", icon: { glyph: "FileScan" }, production: true },
      { name: "VGG16 · CNNs", icon: { glyph: "Layers" }, production: true },
      { name: "LSTM sequence models", icon: { glyph: "Activity" } },
      { name: "TensorFlow Lite", icon: { si: "tensorflow" } },
      { name: "Image processing", icon: { glyph: "Aperture" } },
    ],
  },
  {
    id: "languages",
    title: "Programming Languages",
    blurb: "Thirty-plus languages learned; these are the ones I reach for.",
    skills: [
      { name: "Python", icon: { si: "python" }, production: true },
      { name: "TypeScript", icon: { si: "typescript" }, production: true },
      { name: "JavaScript", icon: { si: "javascript" }, production: true },
      { name: "C++", icon: { si: "cplusplus" } },
      { name: "C", icon: { si: "c" } },
      { name: "C#", icon: { svg: "skills/csharp-original.svg" }, verified: true },
      { name: "Java", icon: { svg: "skills/java-original.svg" }, production: true },
      { name: "Kotlin", icon: { si: "kotlin" } },
      { name: "Dart", icon: { si: "dart" } },
      { name: "Go", icon: { si: "go" } },
      { name: "Swift", icon: { si: "swift" } },
      { name: "PHP", icon: { si: "php" }, production: true },
      { name: "SQL · PL/SQL", icon: { glyph: "Database" }, production: true },
      { name: "R", icon: { si: "r" } },
      { name: "Ruby", icon: { si: "ruby" } },
      { name: "MATLAB", icon: { svg: "skills/matlab.svg" } },
      { name: "Bash · Shell", icon: { si: "gnubash" }, production: true },
      { name: "PowerShell", icon: { glyph: "SquareTerminal" } },
    ],
  },
  {
    id: "web",
    title: "Web & Backend",
    blurb: "Full stack used to be the day job, and it still ships.",
    skills: [
      { name: "React", icon: { si: "react" }, verified: true, production: true },
      { name: "Next.js", icon: { si: "nextdotjs" } },
      { name: "Node.js", icon: { si: "nodedotjs" } },
      { name: "Express", icon: { si: "express" } },
      { name: "FastAPI", icon: { si: "fastapi" } },
      { name: "Flask", icon: { si: "flask" }, production: true },
      { name: "Django", icon: { si: "django" } },
      { name: "Spring Boot", icon: { si: "springboot" }, production: true },
      { name: "Angular", icon: { si: "angular" }, production: true },
      { name: "NestJS", icon: { si: "nestjs" } },
      { name: "Vue.js", icon: { si: "vuedotjs" } },
      { name: "Redux", icon: { si: "redux" } },
      { name: "Tailwind CSS", icon: { si: "tailwindcss" } },
      { name: "HTML5", icon: { si: "html5" } },
      { name: "CSS", icon: { si: "css" }, verified: true },
      { name: "Sass", icon: { si: "sass" } },
      { name: "Bootstrap", icon: { si: "bootstrap" } },
      { name: "WordPress", icon: { si: "wordpress" }, verified: true, production: true },
      { name: "WebSockets · SSE", icon: { glyph: "Radio" } },
      { name: "REST APIs · JSON", icon: { si: "json" }, production: true },
      { name: "XML", icon: { glyph: "Code" }, verified: true },
      { name: "Okta SSO", icon: { si: "okta" }, production: true },
      { name: "Webpack · Babel", icon: { si: "webpack" } },
    ],
  },
  {
    id: "apps",
    title: "Mobile & Desktop",
    blurb: "Native apps on Android and Windows, cross-platform with Flutter.",
    skills: [
      { name: "Flutter", icon: { si: "flutter" } },
      { name: "Android (Java/Kotlin)", icon: { si: "android" } },
      { name: "Jetpack Compose", icon: { si: "jetpackcompose" } },
      { name: "WinUI 3 · .NET", icon: { si: "dotnet" } },
      { name: "Electron", icon: { si: "electron" }, production: true },
      { name: "VST3 · ASIO · WASAPI", icon: { glyph: "AudioWaveform" } },
    ],
  },
  {
    id: "data",
    title: "Data & Databases",
    blurb: "Relational, document and embedded stores.",
    skills: [
      { name: "PostgreSQL", icon: { si: "postgresql" } },
      { name: "MySQL", icon: { si: "mysql" }, production: true },
      { name: "SQLite", icon: { si: "sqlite" }, production: true },
      { name: "MongoDB", icon: { si: "mongodb" } },
      { name: "Firebase", icon: { si: "firebase" } },
      { name: "MariaDB", icon: { si: "mariadb" } },
      { name: "Oracle Database", icon: { svg: "skills/oracle-original.svg" } },
      { name: "Microsoft SQL Server", icon: { svg: "skills/microsoft-sql-server-logo.svg" } },
      { name: "Power BI", icon: { glyph: "ChartColumn" } },
      { name: "Tableau", icon: { glyph: "ChartPie" } },
    ],
  },
  {
    id: "cloud",
    title: "Cloud, DevOps & Edge",
    blurb: "From Azure pipelines to on-prem GPU boxes and kiosks.",
    skills: [
      { name: "Docker", icon: { si: "docker" }, production: true },
      { name: "Kubernetes", icon: { si: "kubernetes" } },
      { name: "AWS", icon: { svg: "skills/amazonwebservices-original-wordmark.svg" } },
      { name: "Microsoft Azure", icon: { svg: "skills/microsoft_azure-icon.svg" }, production: true },
      { name: "Google Cloud", icon: { si: "googlecloud" } },
      { name: "Scaleway", icon: { si: "scaleway" }, production: true },
      { name: "Edge AI inference", icon: { glyph: "MemoryStick" }, production: true },
      { name: "Linux · Ubuntu", icon: { si: "linux" }, production: true },
      { name: "Git · GitHub Actions", icon: { si: "githubactions" }, production: true },
      { name: "Bitbucket CI/CD", icon: { si: "bitbucket" }, production: true },
      { name: "Heroku", icon: { svg: "skills/heroku-icon.svg" } },
      { name: "uv", icon: { si: "uv" } },
    ],
  },
  {
    id: "hardware",
    title: "Hardware & IoT",
    blurb: "Medical devices, single-board computers and embedded systems.",
    skills: [
      { name: "Medical device integration (BT/USB)", icon: { glyph: "Bluetooth" }, production: true },
      { name: "Arduino", icon: { si: "arduino" } },
      { name: "Raspberry Pi · Radxa", icon: { si: "raspberrypi" } },
      { name: "Home Assistant", icon: { si: "homeassistant" } },
      { name: "Digital electronics", icon: { glyph: "CircuitBoard" } },
    ],
  },
  {
    id: "design",
    title: "Design, 3D & Tools",
    blurb: "The craft around the code.",
    skills: [
      { name: "Figma", icon: { si: "figma" } },
      { name: "Framer", icon: { si: "framer" } },
      { name: "Photoshop · Illustrator", icon: { svg: "skills/photoshop-line.svg" }, production: true },
      { name: "Blender", icon: { si: "blender" } },
      { name: "Unreal Engine", icon: { si: "unrealengine" } },
      { name: "Manim", icon: { glyph: "Sigma" } },
      { name: "Postman", icon: { si: "postman" } },
      { name: "Selenium · browser automation", icon: { si: "selenium" } },
      { name: "SEO · digital marketing", icon: { glyph: "TrendingUp" }, production: true },
    ],
  },
];

export const skillCount = skillCategories.reduce((n, c) => n + c.skills.length, 0);
